services:
  - type: web
    name: blinn-project-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install && npm run prisma:generate && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blinn-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true
    github:
      repo: CeoBlinn/blinn-project
      branch: main

databases:
  - name: blinn-db
    plan: free
    region: oregon
    ipAllowList: [] 